// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKO3I0Z4iRgyunCd7KfCTw6wlldol55mw',
    appId: '1:258616587955:web:1beacfc44bd1fca7a522c6',
    messagingSenderId: '258616587955',
    projectId: 'tia-luma',
    authDomain: 'tia-luma.firebaseapp.com',
    storageBucket: 'tia-luma.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_VV5awwPLlbY411dFyH6AvdATJuOeQs',
    appId: '1:258616587955:android:d012f7c91e01671da522c6',
    messagingSenderId: '258616587955',
    projectId: 'tia-luma',
    storageBucket: 'tia-luma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRRxgCUifr9_0WYRNrRxZ8pSASZGxlNg',
    appId: '1:258616587955:ios:bb0edc9ce706e724a522c6',
    messagingSenderId: '258616587955',
    projectId: 'tia-luma',
    storageBucket: 'tia-luma.firebasestorage.app',
    iosBundleId: 'com.example.tiaLuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRRxgCUifr9_0WYRNrRxZ8pSASZGxlNg',
    appId: '1:258616587955:ios:bb0edc9ce706e724a522c6',
    messagingSenderId: '258616587955',
    projectId: 'tia-luma',
    storageBucket: 'tia-luma.firebasestorage.app',
    iosBundleId: 'com.example.tiaLuma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKO3I0Z4iRgyunCd7KfCTw6wlldol55mw',
    appId: '1:258616587955:web:f2aec97dcd37a123a522c6',
    messagingSenderId: '258616587955',
    projectId: 'tia-luma',
    authDomain: 'tia-luma.firebaseapp.com',
    storageBucket: 'tia-luma.firebasestorage.app',
  );

}